# Availability zone key for pods
topologyKey: topology.kubernetes.io/zone

# Harbor portal
ingress:
  enabled: true
  host: harbor.k-space.ee
  tls:
    host: "*.k-space.ee"
  target: traefik.k-space.ee
  class: traefik

# Instantiate proxy cache projects for known Docker registries
caches:
  docker: true
  quay: true

# Mutate pods for cached images
mutation:
  enabled: false
  exclude:
    namespaces:
      - kube-system
      - tigera-operator
      - calico-system
      - metallb-system
      - longhorn-system
      - harbor-operator
      - redis-clusters

# Harbor image repository and tag
image:
  repository: goharbor
  tag: v2.7.1

# Storage options
storage:
  postgres:
    class: shared
    storage: 30Gi
  registry:
    class: shared
    storage: 100Gi

# Harbor projects to initialize
projects: []
