# Availability zone key for pods
topologyKey: topology.kubernetes.io/zone

# Harbor portal
ingress:
  enabled: true
  host: harbor.codemowers.eu
  tls:
    host: "*.codemowers.eu"
  target: traefik.codemowers.eu
  class: shared

# Instantiate proxy cache projects for known Docker registries
caches:
  docker: true
  quay: true

# Mutate pods for cached images
mutation:
  enabled: false
  exclude:
    namespaces:
      - kube-system
      - tigera-operator
      - calico-system
      - metallb-system
      - longhorn-system
      - harbor-operator
      - redis-clusters

# Harbor image repository and tag
image:
  repository: goharbor
  tag: v2.7.1

# Storage options
storage:
  session:
    capacity: 1Gi
  database:
    storageClass: postgres
    capacity: 1Gi
  object:
    bucketClass: shared
    capacity: 100Gi

# Harbor projects to initialize
projects: []
