---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterharborregistries.codemowers.cloud
spec:
  group: codemowers.cloud
  names:
    plural: clusterharborregistries
    singular: clusterharborregistry
    kind: ClusterHarborRegistry
    shortNames:
      - clusterharborregistry
  scope: Cluster
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Status
          jsonPath: .status.registryCreation.state
          type: string
        - name: Errors
          jsonPath: .status.kopf.progress.registryCreation.message
          type: string
        - name: Registry ID
          jsonPath: .status.registryCreation.id
          type: string
        - name: Type
          jsonPath: .spec.type
          type: string
        - name: Endpoint
          jsonPath: .spec.endpoint
          type: string
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                registryCreation:
                  type: object
                  properties:
                    id:
                      type: integer
                    state:
                      type: string
            spec:
              type: object
              required:
                - type
              properties:
                type:
                  type: string
                  enum:
                    - azure-acr
                    - aws-ecr
                    - docker-hub
                    - docker-registry
                    - google-gcr
                    - harbor
                    - quay
                  description: Registry provider
                endpoint:
                  type: string
                  description: Registry endpoint
