---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterharborprojectmembers.codemowers.io
spec:
  group: codemowers.io
  names:
    plural: clusterharborprojectmembers
    singular: clusterharborprojectmember
    kind: ClusterHarborProjectMember
    shortNames:
      - clusterharborprojectmember
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: State
          jsonPath: .status.memberCreation.state
          type: string
        - name: Errors
          jsonPath: .status.kopf.progress.memberCreation.message
          type: string
        - name: Membership ID
          jsonPath: .status.memberCreation.id
          type: integer
        - name: Project
          jsonPath: .spec.project
          type: string
        - name: Username
          jsonPath: .spec.username
          type: string
        - name: Role
          jsonPath: .spec.role
          type: string
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                memberCreation:
                  type: object
                  properties:
                    id:
                      type: integer
                    project_id:
                      type: integer
                    state:
                      type: string
            spec:
              type: object
              required:
                - project
                - username
                - role
              properties:
                project:
                  type: string
                username:
                  type: string
                role:
                  type: string
                  enum:
                    - PROJECT_ADMIN
                    - DEVELOPER
                    - GUEST
                    - MAINTAINER
