---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: harborcredentials.codemowers.io
spec:
  group: codemowers.io
  names:
    plural: harborcredentials
    singular: harborcredential
    kind: HarborCredential
    shortNames:
      - harborcredential
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: State
          jsonPath: .status.credentialCreation.state
          type: string
        - name: Errors
          jsonPath: .status.kopf.progress.credentialCreation.message
          type: string
        - name: Robot ID
          jsonPath: .status.credentialCreation.id
          type: integer
        - name: Project
          jsonPath: .spec.project
          type: string
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                credentialCreation:
                  type: object
                  properties:
                    id:
                      type: integer
                    project:
                      type: string
                    state:
                      type: string
            spec:
              type: object
              required:
                - key
                - project
                - permissions
              properties:
                type:
                  type: string
                key:
                  type: string
                project:
                  type: string
                permissions:
                  type: array
                  items:
                    type: object
                    required:
                      - resource
                      - action
                    properties:
                      resource:
                        type: string
                      action:
                        type: string
