{{ if .Values.caches.quay }}
---
apiVersion: codemowers.cloud/v1beta1
kind: ClusterHarborRegistry
metadata:
  name: quay.io
spec:
  type: quay
  endpoint: https://quay.io
---
apiVersion: codemowers.cloud/v1beta1
kind: ClusterHarborProject
metadata:
  name: quay.io
spec:
  cache: true
  public: true
  quota: 10737418240
{{ end  }}
{{ if .Values.caches.docker }}
---
apiVersion: codemowers.cloud/v1beta1
kind: ClusterHarborRegistry
metadata:
  name: docker.io
spec:
  type: docker-hub
  endpoint: https://docker.io
---
apiVersion: codemowers.cloud/v1beta1
kind: ClusterHarborProject
metadata:
  name: docker.io
spec:
  cache: true
  public: true
  quota: 10737418240
{{ end }}
