apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: harbor
spec:
  postgresVersion: 14
  instances:
    - name: postgres
      replicas: 3
      dataVolumeClaimSpec:
        storageClassName: {{ .Values.storage.postgres.storageClass }}
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.storage.postgres.storage }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: {{ .Values.topologyKey }}
            labelSelector:
              matchLabels:
                postgres-operator.crunchydata.com/cluster: harbor
                postgres-operator.crunchydata.com/instance-set: postgres
  backups:
    pgbackrest:
      global:
        repo1-retention-full: "0"
        repo1-retention-full-type: time
      repos:
        - name: repo1
          schedules:
            full: "0 5 31 2 *"
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 100Mi
